# Generated by Django 4.2.7 on 2025-10-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('rating_change', models.IntegerField()),
                ('rank', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='competitions.competition')),
            ],
            options={
                'db_table': 'rating_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
