# Generated by Django 4.2.7 on 2025-10-31 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['user', '-timestamp'], name='rating_hist_user_id_5612c4_idx'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['competition'], name='rating_hist_competi_7a1697_idx'),
        ),
    ]
