# Generated by Django 4.2.7 on 2025-10-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('submissions_count', models.IntegerField(default=0)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='competitions.competition')),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
            },
        ),
    ]
