# Generated by Django 4.2.7 on 2025-10-31 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='kaggle_team_name',
            field=models.CharField(blank=True, help_text='Team name from Kaggle (for Kaggle-only participants)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='score',
            field=models.FloatField(default=0.0, help_text='Current score'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
