# Generated by Django 4.2.7 on 2025-10-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_submission_id', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('public_score', models.FloatField(blank=True, null=True)),
                ('private_score', models.FloatField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competitions.competition')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submission_time'],
            },
        ),
    ]
