# Generated by Django 4.2.7 on 2025-10-31 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'competition'], name='submissions_user_id_f3bf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['competition', '-score'], name='submissions_competi_92f18d_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-submission_time'], name='submissions_submiss_456a47_idx'),
        ),
    ]
