# Generated by Django 4.2.7 on 2025-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('kaggle_competition_id', models.CharField(max_length=255, unique=True)),
                ('kaggle_url', models.URLField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('rating_weight', models.FloatField(default=1.0)),
                ('max_submissions_per_day', models.IntegerField(default=5)),
                ('evaluation_metric', models.CharField(blank=True, max_length=100)),
                ('prize_pool', models.CharField(blank=True, max_length=255)),
                ('participants_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competitions',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', '-start_date'], name='competition_status_afcb12_idx'), models.Index(fields=['kaggle_competition_id'], name='competition_kaggle__3581dd_idx')],
            },
        ),
    ]
