# Generated by Django 4.2.7 on 2025-10-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('total_prize_pool', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('participants_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competition_events',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status', '-start_date'], name='competition_status_2e25d6_idx'), models.Index(fields=['slug'], name='competition_slug_063b41_idx')],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Parent competition event this competition belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='competitions.competitionevent'),
        ),
    ]
