# Generated by Django 4.2.7 on 2025-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competitionevent_competition_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='higher_is_better',
            field=models.BooleanField(default=True, help_text='True if higher metric value means better performance, False if lower is better'),
        ),
        migrations.AddField(
            model_name='competition',
            name='metric_max_value',
            field=models.FloatField(default=1.0, help_text='Maximum value of the metric for normalization'),
        ),
        migrations.AddField(
            model_name='competition',
            name='metric_min_value',
            field=models.FloatField(default=0.0, help_text='Minimum value of the metric for normalization'),
        ),
        migrations.AddField(
            model_name='competition',
            name='points_for_perfect_score',
            field=models.FloatField(default=100.0, help_text='Maximum points awarded for perfect score (PS points)'),
        ),
    ]
